import { chromium } from '/Users/shivakakkar/Python Projects/Shiva-Teaching Scripts and Handouts/AI Use-Case Workshop/ai-use-case-workshop/node_modules/playwright/index.mjs';
import { mkdir, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';

const out = resolve('verification');
await mkdir(out, {recursive: true});
const browser = await chromium.launch({headless: true, executablePath: '/Users/shivakakkar/Library/Caches/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-mac-arm64/chrome-headless-shell'});
const page = await browser.newPage({viewport: {width: 1365, height: 980}, colorScheme: 'light', reducedMotion: 'reduce'});
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto(pathToFileURL(resolve('dist/index.html')).href);
await page.screenshot({path: `${out}/01-start.png`, fullPage: true});
assert.equal(await page.locator('.active-turn h2').innerText(), 'How would you know hiring got faster?');
assert.equal(await page.locator('.primary-button').isDisabled(), true);
await page.getByRole('button', {name: 'CV-to-offer days', exact: false}).click();
await page.getByRole('button', {name: 'Use this measure'}).click();
assert.equal(await page.locator('.book-count').innerText(), '1 of 6 steps saved');
await page.getByRole('button', {name: 'Feedback is scattered', exact: false}).click();
await page.getByRole('button', {name: 'Investigate this gap'}).click();
await page.getByRole('button', {name: 'Gather feedback', exact: true}).click();
await page.screenshot({path: `${out}/02-journey.png`, fullPage: true});
await page.getByRole('button', {name: 'Record what still remains'}).click();
await page.getByRole('button', {name: 'Source-linked feedback brief', exact: false}).click();
await page.screenshot({path: `${out}/03-comparison.png`, fullPage: true});
await page.getByRole('button', {name: 'Add something in your own words'}).click();
await page.getByLabel('What would you add or change?').fill('Keep the panel’s original disagreement visible.');
await page.getByRole('button', {name: 'Examine this use case'}).click();
await page.getByRole('button', {name: 'Try the process change first', exact: false}).click();
await page.getByRole('button', {name: 'Use this priority'}).click();
await page.getByRole('button', {name: 'Try the shared checklist', exact: false}).click();
await page.getByRole('button', {name: 'Finish our recommendation'}).click();
await page.getByLabel('Give your workbook a name').fill('Our hiring improvement plan');
await page.getByLabel('Group members').fill('Asha, Kabir and Leena (fictional)');
await page.screenshot({path: `${out}/04-complete.png`, fullPage: true});
await page.getByRole('button', {name: 'Read your workbook'}).click();
assert.equal(await page.locator('.book-page').count(), 7);
assert.ok(await page.locator('.book-pages').innerText().then(text => text.includes('Keep the panel’s original disagreement visible.')));
await page.screenshot({path: `${out}/05-book.png`});
await page.pdf({path: `${out}/example-workbook.pdf`, format: 'A4', printBackground: true, preferCSSPageSize: true});
await page.getByRole('button', {name: 'Close', exact: true}).click();
await page.waitForTimeout(50);
assert.equal(await page.evaluate(() => document.activeElement?.textContent?.includes('Read your workbook')), true);
await page.getByRole('button', {name: 'Read 5 earlier answers'}).click();
await page.getByRole('button', {name: 'Edit Step 2: The obstacle'}).click();
assert.equal(await page.locator('.book-count').innerText(), '1 of 6 steps saved');
assert.equal(await page.locator('.active-turn h2').innerText(), 'What is holding the offer back?');
await page.getByRole('button', {name: 'Cancel edit', exact: true}).click();
assert.equal(await page.locator('.book-count').innerText(), '6 of 6 steps saved');
assert.equal(await page.locator('.finished h2').innerText(), 'Your workbook is ready.');
await page.getByRole('button', {name: 'Start again'}).click();
await page.setViewportSize({width: 390, height: 844});
await page.screenshot({path: `${out}/06-mobile.png`, fullPage: true});
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
await page.getByRole('button', {name: 'CV-to-offer days', exact: false}).click();
await page.getByRole('button', {name: 'Add something in your own words'}).click();
await page.getByLabel('What would you add or change?').fill('x'.repeat(600));
await page.getByRole('button', {name: 'Use this measure'}).click();
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
await page.getByRole('button', {name: 'Start again'}).click();
await page.emulateMedia({colorScheme: 'dark'});
await page.screenshot({path: `${out}/07-dark.png`, fullPage: true});
await page.setViewportSize({width: 1365, height: 980});
await page.emulateMedia({colorScheme: 'light'});
await page.keyboard.press('Tab');
assert.ok(await page.evaluate(() => document.activeElement?.tagName === 'BUTTON'));
assert.deepEqual(errors, []);
await writeFile(`${out}/results.json`, JSON.stringify({passed: true, checks: ['six-step process-first journey', 'seven-page book DOM', 'literal note retained', 'edit invalidates later chapters', 'no horizontal overflow at 390px', 'keyboard focus', 'light and dark screenshots', 'no browser errors'], hostIntegrationTested: false, generatedAt: new Date().toISOString()}, null, 2));
await browser.close();
console.log('Concept browser checks passed.');
