// No credentials are interpolated into HTML. The private reading key stays in
// the fragment until this same-origin client sends it in an authorisation header.
export const workspacePage=`<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="robots" content="noindex,nofollow"><meta name="referrer" content="no-referrer"><title>AMA-Groundwork: AI Use-Case Portfolio</title><style>
:root{color-scheme:light dark;--page:#fff;--quiet:#f2f5f5;--ink:#173033;--muted:#5d6d6f;--line:#a7b8ba;--accent:#173033;--accent-ink:#fff}@media(prefers-color-scheme:dark){:root{--page:#191c1d;--quiet:#252a2b;--ink:#f2f4f3;--muted:#b8c0c0;--line:#5b6c6e;--accent:#65cbd5;--accent-ink:#102d32}}*{box-sizing:border-box}body{margin:0;background:var(--page);color:var(--ink);font:16px/1.6 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:1100px;margin:auto;padding:32px 24px}h1{font-size:clamp(24px,4vw,36px);line-height:1.2;margin:0 0 12px}p{margin:10px 0}#status{color:var(--muted)}nav{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin:24px 0}button,select,a.file{font:inherit;color:var(--ink);background:transparent;border:1px solid var(--line);border-radius:4px;padding:11px 16px;text-decoration:none}button,a.file{cursor:pointer}button:hover,a.file:hover{border-color:var(--accent);background:var(--quiet)}button:focus-visible,a:focus-visible,select:focus-visible{outline:3px solid var(--accent);outline-offset:3px}button:disabled{opacity:.5;cursor:wait}.primary{color:var(--accent-ink)!important;background:var(--accent)!important;border-color:var(--accent)!important;font-weight:650}#feedback{min-height:26px}iframe{display:block;width:100%;height:76vh;border:1px solid var(--line);border-radius:4px;background:white}footer{padding:24px 0;color:var(--muted);font-size:14px}#files{display:flex;gap:12px;flex-wrap:wrap}label{display:flex;align-items:center;gap:10px}noscript{display:block;padding:32px}[hidden]{display:none!important}@media(max-width:480px){main{padding:24px 16px}nav{align-items:stretch}nav>*{width:100%}label{justify-content:space-between}iframe{height:70vh}}
</style></head><body><main><h1>AMA-Groundwork: AI Use-Case Portfolio</h1><p id="status" role="status">Opening your saved workbook…</p><nav aria-label="Saved workbook controls"><button id="pdf" class="primary" type="button">Download PDF</button><button id="refresh" type="button">Load latest</button><label>Saved version <select id="versions" aria-label="Saved version"></select></label><button id="json" type="button">Download saved record</button></nav><p id="feedback" role="status"></p><div id="files"></div><iframe id="book" title="AMA-Groundwork workbook" sandbox="" hidden></iframe><footer>Saved until your group explicitly deletes it. This link permits reading and downloads, not changes. Prepared by Dr. Shiva Kakkar.</footer></main><noscript>Enable JavaScript to open this private saved workbook. You can also ask for a PDF in your workshop conversation.</noscript><script>
(()=>{'use strict';const key=location.hash.slice(1);const el=id=>document.getElementById(id);let revision,latest,busy=false;const valid=/^wr1_[A-Za-z0-9_-]{43}$/.test(key);let generation=0;
async function api(path){const response=await fetch(path,{headers:{Authorization:'Bearer '+key},cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});if(!response.ok)throw new Error(response.status===404?'This reading link is unavailable. Ask your group for its saved workbook link.':response.status===429?'Please wait a minute and try again.':'The workbook could not be loaded. Its saved content has not been changed.');return response.json()}
function lock(value){busy=value;for(const id of ['refresh','pdf','json','versions'])el(id).disabled=value||!valid}
async function load(version){if(busy||!valid)return;const token=++generation;lock(true);el('feedback').textContent='';el('files').replaceChildren();try{const data=await api('/api/workbook'+(version===undefined?'':'?revision='+version));if(token!==generation)return;revision=data.revision;latest=data.currentRevision;el('status').textContent=data.groupName+' · '+data.approved+' of 6 steps approved in revision '+revision+(revision<latest?'. Latest saved version: '+latest+'.':'. This is the latest saved version.');el('book').srcdoc=data.html;el('book').hidden=false;el('versions').replaceChildren();for(let n=latest;n>=0;n--){const option=document.createElement('option');option.value=String(n);option.textContent='Revision '+n+(n===latest?' (latest)':'');option.selected=n===revision;el('versions').append(option)}}catch(error){el('feedback').textContent=error.message}finally{lock(false)}}
async function file(kind){if(busy||revision===undefined)return;lock(true);el('feedback').textContent='Preparing your '+(kind==='pdf'?'PDF':'saved record')+'…';try{const response=await fetch('/api/download?revision='+revision+'&kind='+kind,{headers:{Authorization:'Bearer '+key},cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});if(!response.ok)throw new Error(response.status===409?'Approve the first step in your workshop conversation before downloading a PDF.':'The download could not be prepared. Your workbook is still saved; please retry.');const blob=await response.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=kind==='pdf'?'ama-groundwork-r'+revision+'.pdf':'ama-groundwork-revision-'+revision+'.json';a.textContent=kind==='pdf'?'Download PDF':'Download saved record';a.className=kind==='pdf'?'file primary':'file';el('files').replaceChildren(a);el('feedback').textContent='Your file is ready. Select the download below. This workbook stays saved.'}catch(error){el('feedback').textContent=error.message}finally{lock(false)}}
el('refresh').onclick=()=>load();el('versions').onchange=()=>load(Number(el('versions').value));el('pdf').onclick=()=>file('pdf');el('json').onclick=()=>file('json');if(valid)load();else{el('status').textContent='Open the complete private reading link supplied in your workshop conversation.';lock(false)}
})();
</script></body></html>`;

export const workspaceCsp="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; frame-src about: 'self'; font-src data:; img-src data:; object-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'";
